-- ============================================================
-- 07_rbac_masking.sql
-- 7 functional roles, 5 masking policies, scoped grants
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE ARGUS_RISK_COPILOT;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- 1. CREATE ROLES
-- ============================================================
CREATE ROLE IF NOT EXISTS PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER;
CREATE ROLE IF NOT EXISTS FRAUD_ANALYST;
CREATE ROLE IF NOT EXISTS CREDIT_ANALYST;
CREATE ROLE IF NOT EXISTS TREASURY_ANALYST;
CREATE ROLE IF NOT EXISTS AUDITOR;
CREATE ROLE IF NOT EXISTS BRANCH_USER;

-- Role hierarchy: all report to ACCOUNTADMIN
GRANT ROLE PLATFORM_ADMIN     TO ROLE ACCOUNTADMIN;
GRANT ROLE COMPLIANCE_OFFICER  TO ROLE PLATFORM_ADMIN;
GRANT ROLE FRAUD_ANALYST       TO ROLE PLATFORM_ADMIN;
GRANT ROLE CREDIT_ANALYST      TO ROLE PLATFORM_ADMIN;
GRANT ROLE TREASURY_ANALYST    TO ROLE PLATFORM_ADMIN;
GRANT ROLE AUDITOR             TO ROLE PLATFORM_ADMIN;
GRANT ROLE BRANCH_USER         TO ROLE PLATFORM_ADMIN;

-- ============================================================
-- 2. WAREHOUSE GRANTS
-- ============================================================
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE FRAUD_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CREDIT_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TREASURY_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AUDITOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BRANCH_USER;

-- ============================================================
-- 3. DATABASE & SCHEMA GRANTS
-- ============================================================
-- All roles get USAGE on database
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE FRAUD_ANALYST;
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE CREDIT_ANALYST;
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE TREASURY_ANALYST;
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE AUDITOR;
GRANT USAGE ON DATABASE ARGUS_RISK_COPILOT TO ROLE BRANCH_USER;

-- PLATFORM_ADMIN: all schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE ARGUS_RISK_COPILOT TO ROLE PLATFORM_ADMIN;

-- COMPLIANCE_OFFICER: CONFORMED, GOVERNANCE, UNSTRUCTURED, SEMANTIC
GRANT USAGE ON SCHEMA CONFORMED    TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA GOVERNANCE   TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA UNSTRUCTURED TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA SEMANTIC     TO ROLE COMPLIANCE_OFFICER;

-- FRAUD_ANALYST: CONFORMED, GOVERNANCE
GRANT USAGE ON SCHEMA CONFORMED    TO ROLE FRAUD_ANALYST;
GRANT USAGE ON SCHEMA GOVERNANCE   TO ROLE FRAUD_ANALYST;

-- CREDIT_ANALYST: CONFORMED, GOVERNANCE
GRANT USAGE ON SCHEMA CONFORMED    TO ROLE CREDIT_ANALYST;
GRANT USAGE ON SCHEMA GOVERNANCE   TO ROLE CREDIT_ANALYST;

-- TREASURY_ANALYST: CONFORMED
GRANT USAGE ON SCHEMA CONFORMED    TO ROLE TREASURY_ANALYST;

-- AUDITOR: all schemas (read-only)
GRANT USAGE ON ALL SCHEMAS IN DATABASE ARGUS_RISK_COPILOT TO ROLE AUDITOR;

-- BRANCH_USER: CONFORMED only
GRANT USAGE ON SCHEMA CONFORMED    TO ROLE BRANCH_USER;

-- ============================================================
-- 4. TABLE-LEVEL SELECT GRANTS
-- ============================================================

-- PLATFORM_ADMIN: everything
GRANT SELECT ON ALL TABLES IN SCHEMA RAW          TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONFORMED    TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE   TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA UNSTRUCTURED  TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE    TO ROLE PLATFORM_ADMIN;

-- COMPLIANCE_OFFICER: CONFORMED + GOVERNANCE + UNSTRUCTURED
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONFORMED    TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE   TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE    TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN SCHEMA UNSTRUCTURED  TO ROLE COMPLIANCE_OFFICER;

-- FRAUD_ANALYST: CONFORMED (txns, accounts, customers, counterparties, sessions) + GOVERNANCE signals
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONFORMED    TO ROLE FRAUD_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE   TO ROLE FRAUD_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE    TO ROLE FRAUD_ANALYST;

-- CREDIT_ANALYST: CONFORMED (customers, loans, accounts) + GOVERNANCE signals
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONFORMED    TO ROLE CREDIT_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE   TO ROLE CREDIT_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE    TO ROLE CREDIT_ANALYST;

-- TREASURY_ANALYST: CONFORMED (GL, accounts)
GRANT SELECT ON DYNAMIC TABLE CONFORMED.GENERAL_LEDGER_CLEAN TO ROLE TREASURY_ANALYST;
GRANT SELECT ON DYNAMIC TABLE CONFORMED.ACCOUNTS_CLEAN       TO ROLE TREASURY_ANALYST;

-- AUDITOR: read-only on everything
GRANT SELECT ON ALL TABLES IN SCHEMA RAW           TO ROLE AUDITOR;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONFORMED     TO ROLE AUDITOR;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE    TO ROLE AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE    TO ROLE AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA UNSTRUCTURED  TO ROLE AUDITOR;

-- BRANCH_USER: CONFORMED only
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CONFORMED    TO ROLE BRANCH_USER;

-- Future grants for new objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW          TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW          TO ROLE AUDITOR;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CONFORMED TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CONFORMED TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CONFORMED TO ROLE FRAUD_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CONFORMED TO ROLE CREDIT_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CONFORMED TO ROLE AUDITOR;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CONFORMED TO ROLE BRANCH_USER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE TO ROLE PLATFORM_ADMIN;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE TO ROLE FRAUD_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE TO ROLE CREDIT_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE TO ROLE AUDITOR;

-- ============================================================
-- 5. MASKING POLICIES  (using CURRENT_ROLE for precise control)
-- ============================================================
USE SCHEMA GOVERNANCE;

-- 5a. Name masking
CREATE OR REPLACE MASKING POLICY MASK_NAME AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PLATFORM_ADMIN','COMPLIANCE_OFFICER','AUDITOR','ACCOUNTADMIN') THEN val
         ELSE '***MASKED***' END;

-- 5b. Email masking
CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PLATFORM_ADMIN','COMPLIANCE_OFFICER','AUDITOR','ACCOUNTADMIN') THEN val
         ELSE REGEXP_REPLACE(val, '.+@', '****@') END;

-- 5c. Phone masking
CREATE OR REPLACE MASKING POLICY MASK_PHONE AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PLATFORM_ADMIN','COMPLIANCE_OFFICER','AUDITOR','ACCOUNTADMIN') THEN val
         ELSE CONCAT('+91XXXXX', RIGHT(val, 4)) END;

-- 5d. Address masking
CREATE OR REPLACE MASKING POLICY MASK_ADDRESS AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PLATFORM_ADMIN','COMPLIANCE_OFFICER','AUDITOR','ACCOUNTADMIN') THEN val
         ELSE '***REDACTED***' END;

-- 5e. Device ID masking (FRAUD_ANALYST also needs device_id for investigations)
CREATE OR REPLACE MASKING POLICY MASK_DEVICE_ID AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PLATFORM_ADMIN','COMPLIANCE_OFFICER','FRAUD_ANALYST','AUDITOR','ACCOUNTADMIN') THEN val
         ELSE CONCAT('DEV-', RIGHT(SHA2(val), 6)) END;

-- ============================================================
-- 6. APPLY MASKING POLICIES TO CONFORMED DYNAMIC TABLES
-- ============================================================

-- CUSTOMERS_CLEAN
ALTER DYNAMIC TABLE CONFORMED.CUSTOMERS_CLEAN MODIFY COLUMN name    SET MASKING POLICY GOVERNANCE.MASK_NAME;
ALTER DYNAMIC TABLE CONFORMED.CUSTOMERS_CLEAN MODIFY COLUMN email   SET MASKING POLICY GOVERNANCE.MASK_EMAIL;
ALTER DYNAMIC TABLE CONFORMED.CUSTOMERS_CLEAN MODIFY COLUMN phone   SET MASKING POLICY GOVERNANCE.MASK_PHONE;
ALTER DYNAMIC TABLE CONFORMED.CUSTOMERS_CLEAN MODIFY COLUMN address SET MASKING POLICY GOVERNANCE.MASK_ADDRESS;

-- COUNTERPARTIES_CLEAN (name only)
ALTER DYNAMIC TABLE CONFORMED.COUNTERPARTIES_CLEAN MODIFY COLUMN name SET MASKING POLICY GOVERNANCE.MASK_NAME;

-- TRANSACTIONS_CLEAN (device_id)
ALTER DYNAMIC TABLE CONFORMED.TRANSACTIONS_CLEAN MODIFY COLUMN device_id SET MASKING POLICY GOVERNANCE.MASK_DEVICE_ID;

-- DEVICE_SESSIONS_CLEAN (device_id)
ALTER DYNAMIC TABLE CONFORMED.DEVICE_SESSIONS_CLEAN MODIFY COLUMN device_id SET MASKING POLICY GOVERNANCE.MASK_DEVICE_ID;
