-- ============================================================
-- 11_streamlit.sql  —  Streamlit Dashboard Deployment
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE ARGUS_RISK_COPILOT;
USE WAREHOUSE COMPUTE_WH;

-- Stage for Streamlit files
CREATE STAGE IF NOT EXISTS GOVERNANCE.STREAMLIT_STAGE DIRECTORY = (ENABLE = TRUE);

-- Upload files (run from local):
-- PUT 'file://C:/Users/91895/argus/streamlit/streamlit_app.py' @GOVERNANCE.STREAMLIT_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT 'file://C:/Users/91895/argus/streamlit/environment.yml' @GOVERNANCE.STREAMLIT_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Create Streamlit app
CREATE OR REPLACE STREAMLIT GOVERNANCE.ARGUS_DASHBOARD
    ROOT_LOCATION = '@GOVERNANCE.STREAMLIT_STAGE'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = COMPUTE_WH
    COMMENT = 'Argus Risk Copilot — governed fraud, AML, credit risk, and regulatory reporting dashboard';

-- Grants
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE FRAUD_ANALYST;
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE CREDIT_ANALYST;
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE TREASURY_ANALYST;
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE AUDITOR;
GRANT USAGE ON STREAMLIT GOVERNANCE.ARGUS_DASHBOARD TO ROLE BRANCH_USER;
